blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/anthonyshew/turboviz/discussions
    about: Ask questions and discuss topics with other community members
  - name: Chat with other community members
    url: https://discord.com/invite/JMHERJGRkH
    about: The official Anthony Shew Discord community
