name: "Feature Request"
description: "Request a feature or enhancement"
labels: ["needs triage"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for filing an issue 😄!

        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please briefly describe your request."
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed Solution"
      description: |
        Please provide code snippets, gists, or links to the ideal design.
    validations:
      required: true
  - type: "textarea"
    id: "alternatives"
    attributes:
      label: "Alternatives"
      description: |
        What alternative solutions have you considered before making this request?
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        What resources (links, screenshots, etc.) do you have to assist this
        effort?
