name: Canary

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - canary

jobs:
  release:
    name: Publish canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Check prerelease mode
        run: node ./scripts/check-prerelease.js

      - name: Install turbo
        run: pnpm i -g turbo@latest

      - name: Install dependencies
        run: pnpm install

      - name: Build distributable
        run: turbo build --filter=@ashew/turboviz

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          npx changeset version
          npx changeset publish

      - name: Commit back to canary branch
        run: |
          git config --global user.name 'Anthony Shew'
          git config --global user.email 'anthonyshew@users.noreply.github.com'
          git add . :^.npmrc
          git commit -am "[CI] Update canary on branch with version."
          git push origin canary --follow-tags
